name: Tests plataforms
on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configs
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          choco install make
        fi

    - name: Tests
      run: |
        # botar os testes